# Generated by Django 5.0.3 on 2024-03-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_infouser_options_infouser_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='facebook',
            field=models.URLField(default=1, verbose_name='facebook ссылка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='instagram',
            field=models.URLField(default=1, verbose_name='instagram ссылка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='locate',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='phone',
            field=models.CharField(default=111, max_length=255, verbose_name='Телефонный номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='work',
            field=models.CharField(default=1, max_length=255, verbose_name='Профессия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='youtube',
            field=models.URLField(default=1, verbose_name='youtube ссылка'),
            preserve_default=False,
        ),
    ]
