# Generated by Django 5.0.3 on 2024-03-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infouser',
            options={'verbose_name': 'Данные пользователя', 'verbose_name_plural': 'Данные пользователей'},
        ),
        migrations.AddField(
            model_name='infouser',
            name='image',
            field=models.ImageField(default=1, upload_to='info_user/', verbose_name='Фотография пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infouser',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
