# Generated by Django 5.0.3 on 2024-03-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_secondary_infouser_age_infouser_froms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('image', models.ImageField(upload_to='info_user/', verbose_name='Фотография пользователя')),
                ('work', models.CharField(max_length=255, verbose_name='Профессия')),
                ('descriptions', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AlterModelOptions(
            name='secondary',
            options={'verbose_name': 'О пользователе', 'verbose_name_plural': 'О пользователей'},
        ),
    ]
