# Generated by Django 5.0.3 on 2024-03-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_secondary_infouser_age_infouser_froms_and_more'),
        ('base', '0008_testim_alter_secondary_options'),
    ]

    operations = [
    ]
