# Generated by Django 5.0.3 on 2024-03-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_merge_20240323_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook ссылка'),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='froms',
            field=models.CharField(max_length=255, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='image',
            field=models.ImageField(upload_to='info_user/', verbose_name='Фотография пользователя'),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram ссылка'),
        ),
        migrations.AlterField(
            model_name='secondary',
            name='image',
            field=models.ImageField(upload_to='secondary/', verbose_name='Фотография пользователя'),
        ),
        migrations.AlterField(
            model_name='secondary',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Коротко о себе'),
        ),
    ]
